// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkf0p_3WakuoPrpREEYicKzhfHimq4gM',
    appId: '1:574442885042:web:e273f9ce12a7a889a05eab',
    messagingSenderId: '574442885042',
    projectId: 'flutter-chat-app-1c0db',
    authDomain: 'flutter-chat-app-1c0db.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1c0db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk670SJQzWdg_Dvd09tlsRg5grK2gh2JU',
    appId: '1:574442885042:android:f31db7b7d12a0663a05eab',
    messagingSenderId: '574442885042',
    projectId: 'flutter-chat-app-1c0db',
    storageBucket: 'flutter-chat-app-1c0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDimtH-xKu3zjIyzFTxiRRt--eiMn8_Ncs',
    appId: '1:574442885042:ios:6bccc93581a7dfd6a05eab',
    messagingSenderId: '574442885042',
    projectId: 'flutter-chat-app-1c0db',
    storageBucket: 'flutter-chat-app-1c0db.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDimtH-xKu3zjIyzFTxiRRt--eiMn8_Ncs',
    appId: '1:574442885042:ios:55084080740e38d9a05eab',
    messagingSenderId: '574442885042',
    projectId: 'flutter-chat-app-1c0db',
    storageBucket: 'flutter-chat-app-1c0db.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
